version: "v3.0"
name: A more advance YAML file
semaphore_image: standard
blocks:
- build:
      jobs:
        - name: Job from 1st block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
        - name: 2nd job from 1st build block
          commands:
            - cat contents.txt
            - echo $SEMAPHORE_PIPELINE_ID
- build:
      jobs:
        - name: Job from 2nd build block
          commands:
            - echo $SEMAPHORE_PIPELINE_ID
            - echo "This is new"
            - echo bar2
